import {Injectable, inject} from '@angular/core';
import {ElementP} from './elements';
import { FilterService } from './filter.service';

@Injectable({
    providedIn: 'root'
})

export class ElementService{
    filterService: FilterService = inject(FilterService);
    constructor() {}

    getAllElements(): ElementP[]{
      return this.elementList;
    }

  getColor(element: ElementP): string{
      switch(element.type){
        case 'Nonmetal':
            if(this.filterService.isFilterChecked(element.type)){
                return '#808080';
            } else{
                return '#f2bac9';
            }   
        case 'Noble Gas':
            if(this.filterService.isFilterChecked(element.type)){
                return '#808080';
            } else{
                return '#d6c9de';
            }    
        case 'Alkali Metal':
            if(this.filterService.isFilterChecked(element.type)){
                return '#808080';
            } else{
                return '#c8d0e8';
            }               
        case 'Alkaline-Earth Metal':
            if(this.filterService.isFilterChecked(element.type)){
                return '#808080';
            } else{
                return '#bad7f2';
            }            
        case 'Halogen':
            if(this.filterService.isFilterChecked(element.type)){
                return '#808080';
            } else{
                return '#baf2d8';
            }            
        case 'Metal':
            if(this.filterService.isFilterChecked(element.type)){
                return '#808080';
            } else{
                return '#ffb449';
            }          
        case 'Actinide':
            if(this.filterService.isFilterChecked(element.type)){
                return '#808080';
            } else{
                return '#bae5e5';
            }           
        case 'Lanthanide':
            if(this.filterService.isFilterChecked(element.type)){
                return '#808080';
            } else{
                return '#baf2bb';
            }         
        case 'Transition Metal':
            if(this.filterService.isFilterChecked(element.type)){
                return '#808080';
            } else{
                return '#f2e2ba';
            }      
        }
        return 'red';  
  }


  getElement(period: number, group:number): ElementP{
    for (let i = 0; i < this.elementList.length; i++){
        let element = this.elementList[i];
        if(element.uniqueAlignCheck){
            if(element.periodalignval === period && element.groupalignval === group){
                return element;
            }
        }else if (element.period === period && element.group === group){
            return element;
        }
    }

    return this.elementList[0];
}

  filterPeriod(period:number){
    return function(element: ElementP){
        if (element.uniqueAlignCheck){
            return element.periodalignval === period
        }else{
            return element.period === period
        }
    }
  }

  getElementsByPeriod(period: number): ElementP[]{
    return this.elementList.filter(this.filterPeriod(period));
  }

    elementList: ElementP [] = [
        {
        atomicnumber:"0", 
        name:"No Element Found", 
        symbol:"H", 
        atomicMass:"1.00794", 
        period:-1,
        group:-1, 
        state:"Gas", 
        type:"Nonmetal", 
        electronegativity:"2.2", 
        ionizationPotenital:"13.5984", 
        density:"0.00008988", 
        isotopes:"3", 
        discoverer:"Cavendish", 
        discoveryYear:"1766", 
        },
        {
        atomicnumber:"1", 
        name:"Hydrogen", 
        symbol:"H", 
        atomicMass:"1.00794", 
        period:1,
        group:1, 
        state:"Gas", 
        type:"Nonmetal", 
        electronegativity:"2.2", 
        ionizationPotenital:"13.5984", 
        density:"0.00008988", 
        isotopes:"3", 
        discoverer:"Cavendish", 
        discoveryYear:"1766", 
        },
        {
        atomicnumber:"2", 
        name:"Helium", 
        symbol:"He", 
        atomicMass:"4.002602", 
        period:1,
        group:18, 
        state:"Gas", 
        type:"Noble Gas", 
        electronegativity:"0", 
        ionizationPotenital:"24.5874", 
        density:"0.0001785", 
        isotopes:"5", 
        discoverer:"Janssen", 
        discoveryYear:"1868", 
        },
        {
        atomicnumber:"3", 
        name:"Lithium", 
        symbol:"Li", 
        atomicMass:"6.941", 
        period:2,
        group:1, 
        state:"Solid", 
        type:"Alkali Metal", 
        electronegativity:"0.98", 
        ionizationPotenital:"5.3917", 
        density:"0.534", 
        isotopes:"5", 
        discoverer:"Arfvedson", 
        discoveryYear:"1817", 
        },
        {
        atomicnumber:"4", 
        name:"Beryllium", 
        symbol:"Be", 
        atomicMass:"9.012182", 
        period:2,
        group:2, 
        state:"Solid", 
        type:"Alkaline-Earth Metal", 
        electronegativity:"1.57", 
        ionizationPotenital:"9.3227", 
        density:"1.85", 
        isotopes:"6", 
        discoverer:"Vaulquelin", 
        discoveryYear:"1798", 
        },
        {
        atomicnumber:"5", 
        name:"Boron", 
        symbol:"B", 
        atomicMass:"10.811", 
        period:2,
        group:13, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"2.04", 
        ionizationPotenital:"8.298", 
        density:"2.34", 
        isotopes:"6", 
        discoverer:"Gay-Lussac", 
        discoveryYear:"1808", 
        },
        {
        atomicnumber:"6", 
        name:"Carbon", 
        symbol:"C", 
        atomicMass:"12.0107", 
        period:2,
        group:14, 
        state:"Solid", 
        type:"Nonmetal", 
        electronegativity:"2.55", 
        ionizationPotenital:"11.2603", 
        density:"2.267", 
        isotopes:"7", 
        discoverer:"Prehistoric", 
        discoveryYear:"Unknown", 
        },
        {
        atomicnumber:"7", 
        name:"Nitrogen", 
        symbol:"N", 
        atomicMass:"14.0067", 
        period:2,
        group:15, 
        state:"Gas", 
        type:"Nonmetal", 
        electronegativity:"3.04", 
        ionizationPotenital:"14.5341", 
        density:"0.0012506", 
        isotopes:"8", 
        discoverer:"Rutherford", 
        discoveryYear:"1772", 
        },
        {
        atomicnumber:"8", 
        name:"Oxygen", 
        symbol:"O", 
        atomicMass:"15.9994", 
        period:2,
        group:16, 
        state:"Gas", 
        type:"Nonmetal", 
        electronegativity:"3.44", 
        ionizationPotenital:"13.6181", 
        density:"0.001429", 
        isotopes:"8", 
        discoverer:"Priestley/Scheele", 
        discoveryYear:"1774", 
        },
        {
        atomicnumber:"9", 
        name:"Fluorine", 
        symbol:"F", 
        atomicMass:"18.9984032", 
        period:2,
        group:17, 
        state:"Gas", 
        type:"Halogen", 
        electronegativity:"3.98", 
        ionizationPotenital:"17.4228", 
        density:"0.001696", 
        isotopes:"6", 
        discoverer:"Moissan", 
        discoveryYear:"1886", 
        },
        {
        atomicnumber:"10", 
        name:"Neon", 
        symbol:"Ne", 
        atomicMass:"20.1797", 
        period:2,
        group:18, 
        state:"Gas", 
        type:"Noble Gas", 
        electronegativity:"0", 
        ionizationPotenital:"21.5645", 
        density:"0.0008999", 
        isotopes:"8", 
        discoverer:"Ramsay and Travers", 
        discoveryYear:"1898", 
        },
        {
        atomicnumber:"11", 
        name:"Sodium", 
        symbol:"Na", 
        atomicMass:"22.98976928", 
        period:3,
        group:1, 
        state:"Solid", 
        type:"Alkali Metal", 
        electronegativity:"0.93", 
        ionizationPotenital:"5.1391", 
        density:"0.971", 
        isotopes:"7", 
        discoverer:"Davy", 
        discoveryYear:"1807", 
        },
        {
        atomicnumber:"12", 
        name:"Magnesium", 
        symbol:"Mg", 
        atomicMass:"24.305", 
        period:3,
        group:2, 
        state:"Solid", 
        type:"Alkaline-Earth Metal", 
        electronegativity:"1.31", 
        ionizationPotenital:"7.6462", 
        density:"1.738", 
        isotopes:"8", 
        discoverer:"Black", 
        discoveryYear:"1755", 
        },
        {
        atomicnumber:"13", 
        name:"Aluminum", 
        symbol:"Al", 
        atomicMass:"26.9815386", 
        period:3,
        group:13, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"1.61", 
        ionizationPotenital:"5.9858", 
        density:"2.698", 
        isotopes:"8", 
        discoverer:"Whler", 
        discoveryYear:"1827", 
        },
        {
        atomicnumber:"14", 
        name:"Silicon", 
        symbol:"Si", 
        atomicMass:"28.0855", 
        period:3,
        group:14, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"1.9", 
        ionizationPotenital:"8.1517", 
        density:"2.3296", 
        isotopes:"8", 
        discoverer:"Berzelius", 
        discoveryYear:"1824", 
        },
        {
        atomicnumber:"15", 
        name:"Phosphorus", 
        symbol:"P", 
        atomicMass:"30.973762", 
        period:3,
        group:15, 
        state:"Solid", 
        type:"Nonmetal", 
        electronegativity:"2.19", 
        ionizationPotenital:"10.4867", 
        density:"1.82", 
        isotopes:"7", 
        discoverer:"BranBrand", 
        discoveryYear:"1669", 
        },
        {
        atomicnumber:"16", 
        name:"Sulfur", 
        symbol:"S", 
        atomicMass:"32.065", 
        period:3,
        group:16, 
        state:"Solid", 
        type:"Nonmetal", 
        electronegativity:"2.58", 
        ionizationPotenital:"10.36", 
        density:"2.067", 
        isotopes:"10", 
        discoverer:"Prehistoric", 
        discoveryYear:"Unknown", 
        },
        {
        atomicnumber:"17", 
        name:"Chlorine", 
        symbol:"Cl", 
        atomicMass:"35.453", 
        period:3,
        group:17, 
        state:"Gas", 
        type:"Halogen", 
        electronegativity:"3.16", 
        ionizationPotenital:"12.9676", 
        density:"0.003214", 
        isotopes:"11", 
        discoverer:"Scheele", 
        discoveryYear:"1774", 
        },
        {
        atomicnumber:"18", 
        name:"Argon", 
        symbol:"Ar", 
        atomicMass:"39.948", 
        period:3,
        group:18, 
        state:"Gas", 
        type:"Noble Gas", 
        electronegativity:"3.2", 
        ionizationPotenital:"15.7596", 
        density:"0.0017837", 
        isotopes:"8", 
        discoverer:"Rayleigh and Ramsay", 
        discoveryYear:"1894", 
        },
        {
        atomicnumber:"19", 
        name:"Potassium", 
        symbol:"K", 
        atomicMass:"39.0983", 
        period:4,
        group:1, 
        state:"Solid", 
        type:"Alkali Metal", 
        electronegativity:"0.82", 
        ionizationPotenital:"4.3407", 
        density:"0.862", 
        isotopes:"10", 
        discoverer:"Davy", 
        discoveryYear:"1807", 
        },
        {
        atomicnumber:"20", 
        name:"Calcium", 
        symbol:"Ca", 
        atomicMass:"40.078", 
        period:4,
        group:2, 
        state:"Solid", 
        type:"Alkaline-Earth Metal", 
        electronegativity:"1", 
        ionizationPotenital:"6.1132", 
        density:"1.54", 
        isotopes:"14", 
        discoverer:"Davy", 
        discoveryYear:"1808", 
        },
        {
        atomicnumber:"21", 
        name:"Scandium", 
        symbol:"Sc", 
        atomicMass:"44.955912", 
        period:4,
        group:3, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.36", 
        ionizationPotenital:"6.5615", 
        density:"2.989", 
        isotopes:"15", 
        discoverer:"Nilson", 
        discoveryYear:"1878", 
        },
        {
        atomicnumber:"22", 
        name:"Titanium", 
        symbol:"Ti", 
        atomicMass:"47.867", 
        period:4,
        group:4, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.54", 
        ionizationPotenital:"6.8281", 
        density:"4.54", 
        isotopes:"9", 
        discoverer:"Gregor", 
        discoveryYear:"1791", 
        },
        {
        atomicnumber:"23", 
        name:"Vanadium", 
        symbol:"V", 
        atomicMass:"50.9415", 
        period:4,
        group:5, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.63", 
        ionizationPotenital:"6.7462", 
        density:"6.11", 
        isotopes:"9", 
        discoverer:"   del Rio", 
        discoveryYear:"1801", 
        },
        {
        atomicnumber:"24", 
        name:"Chromium", 
        symbol:"Cr", 
        atomicMass:"51.9961", 
        period:4,
        group:6, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.66", 
        ionizationPotenital:"6.7665", 
        density:"7.15", 
        isotopes:"9", 
        discoverer:"Vauquelin", 
        discoveryYear:"1797", 
        },
        {
        atomicnumber:"25", 
        name:"Manganese", 
        symbol:"Mn", 
        atomicMass:"54.938045", 
        period:4,
        group:7, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.55", 
        ionizationPotenital:"7.434", 
        density:"7.44", 
        isotopes:"11", 
        discoverer:"Gahn, Scheele", 
        discoveryYear:"1774", 
        },
        {
        atomicnumber:"26", 
        name:"Iron", 
        symbol:"Fe", 
        atomicMass:"55.845", 
        period:4,
        group:8, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.83", 
        ionizationPotenital:"7.9024", 
        density:"7.874", 
        isotopes:"10", 
        discoverer:"Prehistoric", 
        discoveryYear:"Uknown", 
        },
        {
        atomicnumber:"27", 
        name:"Cobalt", 
        symbol:"Co", 
        atomicMass:"58.933195", 
        period:4,
        group:9, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.88", 
        ionizationPotenital:"7.881", 
        density:"8.86", 
        isotopes:"14", 
        discoverer:"Brandt", 
        discoveryYear:"1735", 
        },
        {
        atomicnumber:"28", 
        name:"Nickel", 
        symbol:"Ni", 
        atomicMass:"58.6934", 
        period:4,
        group:10, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.91", 
        ionizationPotenital:"7.6398", 
        density:"8.912", 
        isotopes:"11", 
        discoverer:"Cronstedt", 
        discoveryYear:"1751", 
        },
        {
        atomicnumber:"29", 
        name:"Copper", 
        symbol:"Cu", 
        atomicMass:"63.546", 
        period:4,
        group:11, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.9", 
        ionizationPotenital:"7.7264", 
        density:"8.96", 
        isotopes:"11", 
        discoverer:"Prehistoric", 
        discoveryYear:"Uknown", 
        },
        {
        atomicnumber:"30", 
        name:"Zinc", 
        symbol:"Zn", 
        atomicMass:"65.38", 
        period:4,
        group:12, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.65", 
        ionizationPotenital:"9.3942", 
        density:"7.134", 
        isotopes:"15", 
        discoverer:"Prehistoric", 
        discoveryYear:"Unknown", 
        },
        {
        atomicnumber:"31", 
        name:"Gallium", 
        symbol:"Ga", 
        atomicMass:"69.723", 
        period:4,
        group:13, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"1.81", 
        ionizationPotenital:"5.9993", 
        density:"5.907", 
        isotopes:"14", 
        discoverer:"de Boisbaudran", 
        discoveryYear:"1875", 
        },
        {
        atomicnumber:"32", 
        name:"Germanium", 
        symbol:"Ge", 
        atomicMass:"72.64", 
        period:4,
        group:14, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"2.01", 
        ionizationPotenital:"7.8994", 
        density:"5.323", 
        isotopes:"17", 
        discoverer:"Winkler", 
        discoveryYear:"1886", 
        },
        {
        atomicnumber:"33", 
        name:"Arsenic", 
        symbol:"As", 
        atomicMass:"74.9216", 
        period:4,
        group:15, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"2.18", 
        ionizationPotenital:"9.7886", 
        density:"5.776", 
        isotopes:"14", 
        discoverer:"Albertus Magnus", 
        discoveryYear:"1250", 
        },
        {
        atomicnumber:"34", 
        name:"Selenium", 
        symbol:"Se", 
        atomicMass:"78.96", 
        period:4,
        group:16, 
        state:"Solid", 
        type:"Nonmetal", 
        electronegativity:"2.55", 
        ionizationPotenital:"9.7524", 
        density:"4.809", 
        isotopes:"20", 
        discoverer:"Berzelius", 
        discoveryYear:"1817", 
        },
        {
        atomicnumber:"35", 
        name:"Bromine", 
        symbol:"Br", 
        atomicMass:"79.904", 
        period:4,
        group:17, 
        state:"Liquid", 
        type:"Halogen", 
        electronegativity:"2.96", 
        ionizationPotenital:"11.8138", 
        density:"3.122", 
        isotopes:"19", 
        discoverer:"Balard", 
        discoveryYear:"1826", 
        },
        {
        atomicnumber:"36", 
        name:"Krypton", 
        symbol:"Kr", 
        atomicMass:"83.798", 
        period:4,
        group:18, 
        state:"Gas", 
        type:"Noble Gas", 
        electronegativity:"3", 
        ionizationPotenital:"13.9996", 
        density:"0.003733", 
        isotopes:"23", 
        discoverer:"Ramsay and Travers", 
        discoveryYear:"1898", 
        },
        {
        atomicnumber:"37", 
        name:"Rubidium", 
        symbol:"Rb", 
        atomicMass:"85.4678", 
        period:5,
        group:1, 
        state:"Solid", 
        type:"Alkali Metal", 
        electronegativity:"0.82", 
        ionizationPotenital:"4.1771", 
        density:"1.532", 
        isotopes:"20", 
        discoverer:"Bunsen and Kirchoff", 
        discoveryYear:"1861", 
        },
        {
        atomicnumber:"38", 
        name:"Strontium", 
        symbol:"Sr", 
        atomicMass:"87.62", 
        period:5,
        group:2, 
        state:"Solid", 
        type:"Alkaline-Earth Metal", 
        electronegativity:"0.95", 
        ionizationPotenital:"5.6949", 
        density:"2.64", 
        isotopes:"18", 
        discoverer:"Davy", 
        discoveryYear:"1808", 
        },
        {
        atomicnumber:"39", 
        name:"Yttrium", 
        symbol:"Y", 
        atomicMass:"88.90585", 
        period:5,
        group:3, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.22", 
        ionizationPotenital:"6.2173", 
        density:"4.469", 
        isotopes:"21", 
        discoverer:"Gadolin", 
        discoveryYear:"1794", 
        },
        {
        atomicnumber:"40", 
        name:"Zirconium", 
        symbol:"Zr", 
        atomicMass:"91.224", 
        period:5,
        group:4, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.33", 
        ionizationPotenital:"6.6339", 
        density:"6.506", 
        isotopes:"20", 
        discoverer:"Klaproth", 
        discoveryYear:"1789", 
        },
        {
        atomicnumber:"41", 
        name:"Niobium", 
        symbol:"Nb", 
        atomicMass:"92.90638", 
        period:5,
        group:5, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.6", 
        ionizationPotenital:"6.7589", 
        density:"8.57", 
        isotopes:"24", 
        discoverer:"Hatchett", 
        discoveryYear:"1801", 
        },
        {
        atomicnumber:"42", 
        name:"Molybdenum", 
        symbol:"Mo", 
        atomicMass:"95.96", 
        period:5,
        group:6, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"2.16", 
        ionizationPotenital:"7.0924", 
        density:"10.22", 
        isotopes:"20", 
        discoverer:"Scheele", 
        discoveryYear:"1778", 
        },
        {
        atomicnumber:"43", 
        name:"Technetium", 
        symbol:"Tc", 
        atomicMass:"98", 
        period:5,
        group:7, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"1.9", 
        ionizationPotenital:"7.28", 
        density:"11.5", 
        isotopes:"23", 
        discoverer:"Perrier and Segr", 
        discoveryYear:"1937", 
        },
        {
        atomicnumber:"44", 
        name:"Ruthenium", 
        symbol:"Ru", 
        atomicMass:"101.07", 
        period:5,
        group:8, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"2.2", 
        ionizationPotenital:"7.3605", 
        density:"12.37", 
        isotopes:"16", 
        discoverer:"Klaus", 
        discoveryYear:"1844", 
        },
        {
        atomicnumber:"45", 
        name:"Rhodium", 
        symbol:"Rh", 
        atomicMass:"102.9055", 
        period:5,
        group:9, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"2.28", 
        ionizationPotenital:"7.4589", 
        density:"12.41", 
        isotopes:"20", 
        discoverer:"Wollaston", 
        discoveryYear:"1803", 
        },
        {
        atomicnumber:"46", 
        name:"Palladium", 
        symbol:"Pd", 
        atomicMass:"106.42", 
        period:5,
        group:10, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"2.2", 
        ionizationPotenital:"8.3369", 
        density:"12.02", 
        isotopes:"21", 
        discoverer:"Wollaston", 
        discoveryYear:"1803", 
        },
        {
        atomicnumber:"47", 
        name:"Silver", 
        symbol:"Ag", 
        atomicMass:"107.8682", 
        period:5,
        group:11, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.93", 
        ionizationPotenital:"7.5762", 
        density:"10.501", 
        isotopes:"27", 
        discoverer:"Prehistoric", 
        discoveryYear:"Unknown", 
        },
        {
        atomicnumber:"48", 
        name:"Cadmium", 
        symbol:"Cd", 
        atomicMass:"112.411", 
        period:5,
        group:12, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.69", 
        ionizationPotenital:"8.9938", 
        density:"8.69", 
        isotopes:"22", 
        discoverer:"Stromeyer", 
        discoveryYear:"1817", 
        },
        {
        atomicnumber:"49", 
        name:"Indium", 
        symbol:"In", 
        atomicMass:"114.818", 
        period:5,
        group:13, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"1.78", 
        ionizationPotenital:"5.7864", 
        density:"7.31", 
        isotopes:"34", 
        discoverer:"Reich and Richter", 
        discoveryYear:"1863", 
        },
        {
        atomicnumber:"50", 
        name:"Tin", 
        symbol:"Sn", 
        atomicMass:"118.71", 
        period:5,
        group:14, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"1.96", 
        ionizationPotenital:"7.3439", 
        density:"7.287", 
        isotopes:"28", 
        discoverer:"Prehistoric", 
        discoveryYear:"Unknown", 
        },
        {
        atomicnumber:"51", 
        name:"Antimony", 
        symbol:"Sb", 
        atomicMass:"121.76", 
        period:5,
        group:15, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"2.05", 
        ionizationPotenital:"8.6084", 
        density:"6.685", 
        isotopes:"29", 
        discoverer:"Early historic times", 
        discoveryYear:"Unknown", 
        },
        {
        atomicnumber:"52", 
        name:"Tellurium", 
        symbol:"Te", 
        atomicMass:"127.6", 
        period:5,
        group:16, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"2.1", 
        ionizationPotenital:"9.0096", 
        density:"6.232", 
        isotopes:"29", 
        discoverer:"von Reichenstein", 
        discoveryYear:"1782", 
        },
        {
        atomicnumber:"53", 
        name:"Iodine", 
        symbol:"I", 
        atomicMass:"126.90447", 
        period:5,
        group:17, 
        state:"Solid", 
        type:"Halogen", 
        electronegativity:"2.66", 
        ionizationPotenital:"10.4513", 
        density:"4.93", 
        isotopes:"24", 
        discoverer:"Courtois", 
        discoveryYear:"1811", 
        },
        {
        atomicnumber:"54", 
        name:"Xenon", 
        symbol:"Xe", 
        atomicMass:"131.293", 
        period:5,
        group:18, 
        state:"Gas", 
        type:"Noble Gas", 
        electronegativity:"2.6", 
        ionizationPotenital:"12.1298", 
        density:"0.005887", 
        isotopes:"31", 
        discoverer:"Ramsay and Travers", 
        discoveryYear:"1898", 
        },
        {
        atomicnumber:"55", 
        name:"Cesium", 
        symbol:"Cs", 
        atomicMass:"132.9054519", 
        period:6,
        group:1, 
        state:"Solid", 
        type:"Alkali Metal", 
        electronegativity:"0.79", 
        ionizationPotenital:"3.8939", 
        density:"1.873", 
        isotopes:"22", 
        discoverer:"Bunsen and Kirchoff", 
        discoveryYear:"1860", 
        },
        {
        atomicnumber:"56", 
        name:"Barium", 
        symbol:"Ba", 
        atomicMass:"137.327", 
        period:6,
        group:2, 
        state:"Solid", 
        type:"Alkaline-Earth Metal", 
        electronegativity:"0.89", 
        ionizationPotenital:"5.2117", 
        density:"3.594", 
        isotopes:"25", 
        discoverer:"Davy", 
        discoveryYear:"1808", 
        },
        {
        atomicnumber:"57", 
        name:"Lanthanum", 
        symbol:"La", 
        atomicMass:"138.90547", 
        period:6,
        group:3, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.1", 
        ionizationPotenital:"5.5769", 
        density:"6.145", 
        isotopes:"19", 
        discoverer:"Mosander", 
        discoveryYear:"1839", 
        },
        {
        atomicnumber:"58", 
        name:"Cerium", 
        symbol:"Ce", 
        atomicMass:"140.116", 
        period:6,
        group:19, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.12", 
        ionizationPotenital:"5.5387", 
        density:"6.77", 
        isotopes:"19", 
        discoverer:"Berzelius", 
        discoveryYear:"1803", 
        periodalignval:8, 
        groupalignval:4, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"59", 
        name:"Praseodymium", 
        symbol:"Pr", 
        atomicMass:"140.90765", 
        period:6,
        group:20, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.13", 
        ionizationPotenital:"5.473", 
        density:"6.773", 
        isotopes:"15", 
        discoverer:"von Welsbach", 
        discoveryYear:"1885", 
        periodalignval:8, 
        groupalignval:5, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"60", 
        name:"Neodymium", 
        symbol:"Nd", 
        atomicMass:"144.242", 
        period:6,
        group:21, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.14", 
        ionizationPotenital:"5.525", 
        density:"7.007", 
        isotopes:"16", 
        discoverer:"von Welsbach", 
        discoveryYear:"1885", 
        periodalignval:8, 
        groupalignval:6, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"61", 
        name:"Promethium", 
        symbol:"Pm", 
        atomicMass:"145", 
        period:6,
        group:22, 
        state:"Artificial", 
        type:"Lanthanide", 
        electronegativity:"1.13", 
        ionizationPotenital:"5.582", 
        density:"7.26", 
        isotopes:"14", 
        discoverer:"Marinsky et al.", 
        discoveryYear:"1945", 
        periodalignval:8, 
        groupalignval:7, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"62", 
        name:"Samarium", 
        symbol:"Sm", 
        atomicMass:"150.36", 
        period:6,
        group:23, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.17", 
        ionizationPotenital:"5.6437", 
        density:"7.52", 
        isotopes:"17", 
        discoverer:"Boisbaudran", 
        discoveryYear:"1879", 
        periodalignval:8, 
        groupalignval:8, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"63", 
        name:"Europium", 
        symbol:"Eu", 
        atomicMass:"151.964", 
        period:6,
        group:24, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.2", 
        ionizationPotenital:"5.6704", 
        density:"5.243", 
        isotopes:"21", 
        discoverer:"Demarcay", 
        discoveryYear:"1901", 
        periodalignval:8, 
        groupalignval:9, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"64", 
        name:"Gadolinium", 
        symbol:"Gd", 
        atomicMass:"157.25", 
        period:6,
        group:25, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.2", 
        ionizationPotenital:"6.1501", 
        density:"7.895", 
        isotopes:"17", 
        discoverer:"de Marignac", 
        discoveryYear:"1880", 
        periodalignval:8, 
        groupalignval:10, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"65", 
        name:"Terbium", 
        symbol:"Tb", 
        atomicMass:"158.92535", 
        period:6,
        group:26, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.2", 
        ionizationPotenital:"5.8638", 
        density:"8.229", 
        isotopes:"24", 
        discoverer:"Mosander", 
        discoveryYear:"1843", 
        periodalignval:8, 
        groupalignval:11, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"66", 
        name:"Dysprosium", 
        symbol:"Dy", 
        atomicMass:"162.5", 
        period:6,
        group:27, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.22", 
        ionizationPotenital:"5.9389", 
        density:"8.55", 
        isotopes:"21", 
        discoverer:"de Boisbaudran", 
        discoveryYear:"1886", 
        periodalignval:8, 
        groupalignval:12, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"67", 
        name:"Holmium", 
        symbol:"Ho", 
        atomicMass:"164.93032", 
        period:6,
        group:28, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.23", 
        ionizationPotenital:"6.0215", 
        density:"8.795", 
        isotopes:"29", 
        discoverer:"Delafontaine and Soret", 
        discoveryYear:"1878", 
        periodalignval:8, 
        groupalignval:13, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"68", 
        name:"Erbium", 
        symbol:"Er", 
        atomicMass:"167.259", 
        period:6,
        group:29, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.24", 
        ionizationPotenital:"6.1077", 
        density:"9.066", 
        isotopes:"16", 
        discoverer:"Mosander", 
        discoveryYear:"1843", 
        periodalignval:8, 
        groupalignval:14, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"69", 
        name:"Thulium", 
        symbol:"Tm", 
        atomicMass:"168.93421", 
        period:6,
        group:30, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.25", 
        ionizationPotenital:"6.1843", 
        density:"9.321", 
        isotopes:"18", 
        discoverer:"Cleve", 
        discoveryYear:"1879", 
        periodalignval:8, 
        groupalignval:15, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"70", 
        name:"Ytterbium", 
        symbol:"Yb", 
        atomicMass:"173.054", 
        period:6,
        group:31, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.1", 
        ionizationPotenital:"6.2542", 
        density:"6.965", 
        isotopes:"16", 
        discoverer:"Marignac", 
        discoveryYear:"1878", 
        periodalignval:8, 
        groupalignval:16, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"71", 
        name:"Lutetium", 
        symbol:"Lu", 
        atomicMass:"174.9668", 
        period:6,
        group:32, 
        state:"Solid", 
        type:"Lanthanide", 
        electronegativity:"1.27", 
        ionizationPotenital:"5.4259", 
        density:"9.84", 
        isotopes:"22", 
        discoverer:"Urbain/ von Welsbach", 
        discoveryYear:"1907", 
        periodalignval:8, 
        groupalignval:17, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"72", 
        name:"Hafnium", 
        symbol:"Hf", 
        atomicMass:"178.49", 
        period:6,
        group:4, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.3", 
        ionizationPotenital:"6.8251", 
        density:"13.31", 
        isotopes:"17", 
        discoverer:"Coster and von Hevesy", 
        discoveryYear:"1923", 
        },
        {
        atomicnumber:"73", 
        name:"Tantalum", 
        symbol:"Ta", 
        atomicMass:"180.94788", 
        period:6,
        group:5, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.5", 
        ionizationPotenital:"7.5496", 
        density:"16.654", 
        isotopes:"19", 
        discoverer:"Ekeberg", 
        discoveryYear:"1801", 
        },
        {
        atomicnumber:"74", 
        name:"Wolfram", 
        symbol:"W", 
        atomicMass:"183.84", 
        period:6,
        group:6, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"2.36", 
        ionizationPotenital:"7.864", 
        density:"19.25", 
        isotopes:"22", 
        discoverer:"J. and F. d'Elhuyar", 
        discoveryYear:"1783", 
        },
        {
        atomicnumber:"75", 
        name:"Rhenium", 
        symbol:"Re", 
        atomicMass:"186.207", 
        period:6,
        group:7, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"1.9", 
        ionizationPotenital:"7.8335", 
        density:"21.02", 
        isotopes:"21", 
        discoverer:"Noddack, Berg, and Tacke", 
        discoveryYear:"1925", 
        },
        {
        atomicnumber:"76", 
        name:"Osmium", 
        symbol:"Os", 
        atomicMass:"190.23", 
        period:6,
        group:8, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"2.2", 
        ionizationPotenital:"8.4382", 
        density:"22.61", 
        isotopes:"19", 
        discoverer:"Tennant", 
        discoveryYear:"1803", 
        },
        {
        atomicnumber:"77", 
        name:"Iridium", 
        symbol:"Ir", 
        atomicMass:"192.217", 
        period:6,
        group:9, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"2.2", 
        ionizationPotenital:"8.967", 
        density:"22.56", 
        isotopes:"25", 
        discoverer:"Tennant", 
        discoveryYear:"1804", 
        },
        {
        atomicnumber:"78", 
        name:"Platinum", 
        symbol:"Pt", 
        atomicMass:"195.084", 
        period:6,
        group:10, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"2.28", 
        ionizationPotenital:"8.9587", 
        density:"21.46", 
        isotopes:"32", 
        discoverer:"Ulloa/Wood", 
        discoveryYear:"1735", 
        },
        {
        atomicnumber:"79", 
        name:"Gold", 
        symbol:"Au", 
        atomicMass:"196.966569", 
        period:6,
        group:11, 
        state:"Solid", 
        type:"Transition Metal", 
        electronegativity:"2.54", 
        ionizationPotenital:"9.2255", 
        density:"19.282", 
        isotopes:"21", 
        discoverer:"Prehistoric", 
        discoveryYear:"Unknown", 
        },
        {
        atomicnumber:"80", 
        name:"Mercury", 
        symbol:"Hg", 
        atomicMass:"200.59", 
        period:6,
        group:12, 
        state:"Liquid", 
        type:"Transition Metal", 
        electronegativity:"2", 
        ionizationPotenital:"10.4375", 
        density:"13.5336", 
        isotopes:"26", 
        discoverer:"Prehistoric", 
        discoveryYear:"Unknown", 
        },
        {
        atomicnumber:"81", 
        name:"Thallium", 
        symbol:"Tl", 
        atomicMass:"204.3833", 
        period:6,
        group:13, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"2.04", 
        ionizationPotenital:"6.1082", 
        density:"11.85", 
        isotopes:"28", 
        discoverer:"Crookes", 
        discoveryYear:"1861", 
        },
        {
        atomicnumber:"82", 
        name:"Lead", 
        symbol:"Pb", 
        atomicMass:"207.2", 
        period:6,
        group:14, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"2.33", 
        ionizationPotenital:"7.4167", 
        density:"11.342", 
        isotopes:"29", 
        discoverer:"Prehistoric", 
        discoveryYear:"Unknown", 
        },
        {
        atomicnumber:"83", 
        name:"Bismuth", 
        symbol:"Bi", 
        atomicMass:"208.9804", 
        period:6,
        group:15, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"2.02", 
        ionizationPotenital:"7.2856", 
        density:"9.807", 
        isotopes:"19", 
        discoverer:"Geoffroy the Younger", 
        discoveryYear:"1753", 
        },
        {
        atomicnumber:"84", 
        name:"Polonium", 
        symbol:"Po", 
        atomicMass:"210", 
        period:6,
        group:16, 
        state:"Solid", 
        type:"Metal", 
        electronegativity:"2", 
        ionizationPotenital:"8.417", 
        density:"9.32", 
        isotopes:"34", 
        discoverer:"Curie", 
        discoveryYear:"1898", 
        },
        {
        atomicnumber:"85", 
        name:"Astatine", 
        symbol:"At", 
        atomicMass:"210", 
        period:6,
        group:17, 
        state:"Solid", 
        type:"Halogen", 
        electronegativity:"2.2", 
        ionizationPotenital:"9.3", 
        density:"7", 
        isotopes:"21", 
        discoverer:"Corson et al.", 
        discoveryYear:"1940", 
        },
        {
        atomicnumber:"86", 
        name:"Radon", 
        symbol:"Rn", 
        atomicMass:"222", 
        period:6,
        group:18, 
        state:"Gas", 
        type:"Noble Gas", 
        electronegativity:"2.2", 
        ionizationPotenital:"10.7485", 
        density:"0.00973", 
        isotopes:"20", 
        discoverer:"Dorn", 
        discoveryYear:"1900", 
        },
        {
        atomicnumber:"87", 
        name:"Francium", 
        symbol:"Fr", 
        atomicMass:"223", 
        period:7,
        group:1, 
        state:"Solid", 
        type:"Alkali Metal", 
        electronegativity:"0.7", 
        ionizationPotenital:"4.0727", 
        density:"1.87", 
        isotopes:"21", 
        discoverer:"Perey", 
        discoveryYear:"1939", 
        },
        {
        atomicnumber:"88", 
        name:"Radium", 
        symbol:"Ra", 
        atomicMass:"226", 
        period:7,
        group:2, 
        state:"Solid", 
        type:"Alkaline-Earth Metal", 
        electronegativity:"0.9", 
        ionizationPotenital:"5.2784", 
        density:"5.5", 
        isotopes:"15", 
        discoverer:"Pierre and Marie Curie", 
        discoveryYear:"1898", 
        },
        {
        atomicnumber:"89", 
        name:"Actinium", 
        symbol:"Ac", 
        atomicMass:"227", 
        period:7,
        group:3, 
        state:"Solid", 
        type:"Actinide", 
        electronegativity:"1.1", 
        ionizationPotenital:"5.17", 
        density:"10.07", 
        isotopes:"11", 
        discoverer:"Debierne/Giesel", 
        discoveryYear:"1899", 
        },
        {
        atomicnumber:"90", 
        name:"Thorium", 
        symbol:"Th", 
        atomicMass:"232.03806", 
        period:7,
        group:19, 
        state:"Solid", 
        type:"Actinide", 
        electronegativity:"1.3", 
        ionizationPotenital:"6.3067", 
        density:"11.72", 
        isotopes:"12", 
        discoverer:"Berzelius", 
        discoveryYear:"1828", 
        periodalignval:9, 
        groupalignval:4, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"91", 
        name:"Protactinium", 
        symbol:"Pa", 
        atomicMass:"231.03588", 
        period:7,
        group:20, 
        state:"Solid", 
        type:"Actinide", 
        electronegativity:"1.5", 
        ionizationPotenital:"5.89", 
        density:"15.37", 
        isotopes:"14", 
        discoverer:"Hahn and Meitner", 
        discoveryYear:"1917", 
        periodalignval:9, 
        groupalignval:5, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"92", 
        name:"Uranium", 
        symbol:"U", 
        atomicMass:"238.02891", 
        period:7,
        group:21, 
        state:"Solid", 
        type:"Actinide", 
        electronegativity:"1.38", 
        ionizationPotenital:"6.1941", 
        density:"18.95", 
        isotopes:"15", 
        discoverer:"Peligot", 
        discoveryYear:"1841", 
        periodalignval:9, 
        groupalignval:6, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"93", 
        name:"Neptunium", 
        symbol:"Np", 
        atomicMass:"237", 
        period:7,
        group:22, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.36", 
        ionizationPotenital:"6.2657", 
        density:"20.45", 
        isotopes:"153", 
        discoverer:"McMillan and Abelson", 
        discoveryYear:"1940", 
        periodalignval:9, 
        groupalignval:7, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"94", 
        name:"Plutonium", 
        symbol:"Pu", 
        atomicMass:"244", 
        period:7,
        group:23, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.28", 
        ionizationPotenital:"6.0262", 
        density:"19.84", 
        isotopes:"163", 
        discoverer:"Seaborg et al.", 
        discoveryYear:"1940", 
        periodalignval:9, 
        groupalignval:8, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"95", 
        name:"Americium", 
        symbol:"Am", 
        atomicMass:"243", 
        period:7,
        group:24, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.3", 
        ionizationPotenital:"5.9738", 
        density:"13.69", 
        isotopes:"133", 
        discoverer:"Seaborg et al.", 
        discoveryYear:"1944", 
        periodalignval:9, 
        groupalignval:9, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"96", 
        name:"Curium", 
        symbol:"Cm", 
        atomicMass:"247", 
        period:7,
        group:25, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.3", 
        ionizationPotenital:"5.9915", 
        density:"13.51", 
        isotopes:"133", 
        discoverer:"Seaborg et al.", 
        discoveryYear:"1944", 
        periodalignval:9, 
        groupalignval:10, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"97", 
        name:"Berkelium", 
        symbol:"Bk", 
        atomicMass:"247", 
        period:7,
        group:26, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.3", 
        ionizationPotenital:"6.1979", 
        density:"14.79", 
        isotopes:"83", 
        discoverer:"Seaborg et al.", 
        discoveryYear:"1949", 
        periodalignval:9, 
        groupalignval:11, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"98", 
        name:"Californium", 
        symbol:"Cf", 
        atomicMass:"251", 
        period:7,
        group:27, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.3", 
        ionizationPotenital:"6.2817", 
        density:"15.1", 
        isotopes:"123", 
        discoverer:"Seaborg et al.", 
        discoveryYear:"1950", 
        periodalignval:9, 
        groupalignval:12, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"99", 
        name:"Einsteinium", 
        symbol:"Es", 
        atomicMass:"252", 
        period:7,
        group:28, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.3", 
        ionizationPotenital:"6.42", 
        density:"13.5", 
        isotopes:"123", 
        discoverer:"Ghiorso et al.", 
        discoveryYear:"1952", 
        periodalignval:9, 
        groupalignval:13, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"100", 
        name:"Fermium", 
        symbol:"Fm", 
        atomicMass:"257", 
        period:7,
        group:29, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.3", 
        ionizationPotenital:"6.5", 
        density:"N/A", 
        isotopes:"103", 
        discoverer:"Ghiorso et al.", 
        discoveryYear:"1953", 
        periodalignval:9, 
        groupalignval:14, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"101", 
        name:"Mendelevium", 
        symbol:"Md", 
        atomicMass:"258", 
        period:7,
        group:30, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.3", 
        ionizationPotenital:"6.58", 
        density:"N/A", 
        isotopes:"33", 
        discoverer:"Ghiorso et al.", 
        discoveryYear:"1955", 
        periodalignval:9, 
        groupalignval:15, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"102", 
        name:"Nobelium", 
        symbol:"No", 
        atomicMass:"259", 
        period:7,
        group:31, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"1.3", 
        ionizationPotenital:"6.65", 
        density:"N/A", 
        isotopes:"73", 
        discoverer:"Ghiorso et al.", 
        discoveryYear:"1958", 
        periodalignval:9, 
        groupalignval:16, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"103", 
        name:"Lawrencium", 
        symbol:"Lr", 
        atomicMass:"262", 
        period:7,
        group:32, 
        state:"Artificial", 
        type:"Actinide", 
        electronegativity:"N/A", 
        ionizationPotenital:"4.9", 
        density:"N/A", 
        isotopes:"203", 
        discoverer:"Ghiorso et al.", 
        discoveryYear:"1961", 
        periodalignval:9, 
        groupalignval:17, 
        uniqueAlignCheck:true,
        },
        {
        atomicnumber:"104", 
        name:"Rutherfordium", 
        symbol:"Rf", 
        atomicMass:"261", 
        period:7,
        group:4, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"18.1", 
        isotopes:"No Stable", 
        discoverer:"Ghiorso et al.", 
        discoveryYear:"1969", 
        },
        {
        atomicnumber:"105", 
        name:"Dubnium", 
        symbol:"Db", 
        atomicMass:"262", 
        period:7,
        group:5, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"39", 
        isotopes:"No Stable", 
        discoverer:"Ghiorso et al.", 
        discoveryYear:"1970", 
        },
        {
        atomicnumber:"106", 
        name:"Seaborgium", 
        symbol:"Sg", 
        atomicMass:"266", 
        period:7,
        group:6, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"35", 
        isotopes:"No Stable", 
        discoverer:"Ghiorso et al.", 
        discoveryYear:"1974", 
        },
        {
        atomicnumber:"107", 
        name:"Bohrium", 
        symbol:"Bh", 
        atomicMass:"264", 
        period:7,
        group:7, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"37", 
        isotopes:"No Stable", 
        discoverer:"Armbruster and Mnzenberg", 
        discoveryYear:"1981", 
        },
        {
        atomicnumber:"108", 
        name:"Hassium", 
        symbol:"Hs", 
        atomicMass:"267", 
        period:7,
        group:8, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"41", 
        isotopes:"No Stable", 
        discoverer:"Armbruster and Mnzenberg", 
        discoveryYear:"1983", 
        },
        {
        atomicnumber:"109", 
        name:"Meitnerium", 
        symbol:"Mt", 
        atomicMass:"268", 
        period:7,
        group:9, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"35", 
        isotopes:"No Stable", 
        discoverer:"GSI, Darmstadt, West Germany", 
        discoveryYear:"1982", 
        },
        {
        atomicnumber:"110", 
        name:"Darmstadtium ", 
        symbol:"Ds ", 
        atomicMass:"271", 
        period:7,
        group:10, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"N/A", 
        isotopes:"No Stable", 
        discoverer:"GSI, Darmstadt, West Germany", 
        discoveryYear:"1994", 
        },
        {
        atomicnumber:"111", 
        name:"Roentgenium ", 
        symbol:"Rg ", 
        atomicMass:"272", 
        period:7,
        group:11, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"N/A", 
        isotopes:"No Stable", 
        discoverer:"GSI, Darmstadt, West Germany", 
        discoveryYear:"1994", 
        },
        {
        atomicnumber:"112", 
        name:"Copernicium ", 
        symbol:"Cn ", 
        atomicMass:"285", 
        period:7,
        group:12, 
        state:"Artificial", 
        type:"Transition Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"N/A", 
        isotopes:"No Stable", 
        discoverer:"GSI, Darmstadt, West Germany", 
        discoveryYear:"1996", 
        },
        {
        atomicnumber:"113", 
        name:"Ununtrium ", 
        symbol:"Uut ", 
        atomicMass:"284", 
        period:7,
        group:13, 
        state:"Artificial", 
        type:"Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"N/A", 
        isotopes:"No Stable", 
        discoverer:"Joint Inst. for Nuclear Research, Lawrence Livermore ational Laboratory", 
        discoveryYear:"2004", 
        },
        {
        atomicnumber:"114", 
        name:"Ununquadium ", 
        symbol:"Uuq ", 
        atomicMass:"289", 
        period:7,
        group:14, 
        state:"Artificial", 
        type:"Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"N/A", 
        isotopes:"No Stable", 
        discoverer:"Joint Inst. for Nuclear Research", 
        discoveryYear:"1998", 
        },
        {
        atomicnumber:"115", 
        name:"Ununpentium ", 
        symbol:"Uup ", 
        atomicMass:"288", 
        period:7,
        group:15, 
        state:"Artificial", 
        type:"Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"N/A", 
        isotopes:"No Stable", 
        discoverer:"Joint Inst. for Nuclear Research, Lawrence Livermore ational Laboratory", 
        discoveryYear:"2003", 
        },
        {
        atomicnumber:"116", 
        name:"Ununhexium ", 
        symbol:"Uuh ", 
        atomicMass:"292", 
        period:7,
        group:16, 
        state:"Artificial", 
        type:"Metal", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"N/A", 
        isotopes:"No Stable", 
        discoverer:"Joint Inst. for Nuclear Research", 
        discoveryYear:"2000", 
        },
        {
        atomicnumber:"117", 
        name:"Ununseptium ", 
        symbol:"Uus ", 
        atomicMass:"295", 
        period:7,
        group:17, 
        state:"Artificial", 
        type:"Halogen", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"N/A", 
        isotopes:"No Stable", 
        discoverer:"Joint Inst. for Nuclear Research", 
        discoveryYear:"2010", 
        },
        {
        atomicnumber:"118", 
        name:"Ununoctium ", 
        symbol:"Uuo ", 
        atomicMass:"294", 
        period:7,
        group:18, 
        state:"Artificial", 
        type:"Noble Gas", 
        electronegativity:"N/A", 
        ionizationPotenital:"N/A", 
        density:"N/A", 
        isotopes:"No Stable", 
        discoverer:"Joint Inst. for Nuclear Research", 
        discoveryYear:"2002", 
        },
        
    ]
}